[build]
publish = "frontend/build"
# Default build command.
command = "npm run build"

[functions]
directory = "functions"
external_node_modules = ["electron"]

[context.dev.functions]
directory = "functions"